### ISSUE TITLE
本地运行main后报错

### ISSUE THREAD

**Issue by Y3PM** [EvilCult/iptv-m3u-maker#11]
已经全部检查完成了，然后报错了。Python3.7
Checking[ 670 / 670 ]: 黑龙江
....
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1056)>

**Comment by EvilCult** [comment]
报错的是“listb”这块的代码.
原因很简单......
那个资源站关了.....
「暂时」暴力的注释掉这个代码块就可以了...
见commit : 9b98a54d7019f2f8620c81b4349b9b5a77aad37d
