### ISSUE TITLE
采集的视频源没更新

### ISSUE THREAD

**Issue by snyzf** [EvilCult/iptv-m3u-maker#15]
版主好，发现你采集的这几个视频源都基本没怎么更新。
建议上这两个视频源。看着更新挺快的。
http://m.iptv206.com/
http://www.lizhizu.com/

**Comment by EvilCult** [comment]
嗯嗯嗯~~
http://m.iptv206.com/
这个看着不错啊, 争取在下个版本里加入,多谢分享

**Comment by EvilCult** [comment]
#22 加入了一个数据源,另一个貌似也挂了

**Comment by snyzf** [comment]
荔枝的好像挂了。我很久没采集了。

**Comment by snyzf** [comment]
> #22 加入了一个数据源,另一个貌似也挂了

我现在自己不采集了。直接用这个的。
https://github.com/homenet6/homenet6.github.io
有专人更新
