### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 8: illegal multibyte sequence

### ISSUE THREAD

**Issue by kwshare** [EvilCult/iptv-m3u-maker#16]
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    obj.run()
  File "main.py", line 37, in run
    urlList = Dotpy.getSource()
  File "D:\Users\下载\ww_iptvm3ulist_com\iptv-m3u-maker-master\plugins\dotpy.py", line 19, in getSource
    lines = f.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 8: illegal multibyte sequence

**Comment by snyzf** [comment]
暴力注销掉。那个源已经关闭了。所以出错。

**Comment by EvilCult** [comment]
我看一下,下个版本迭代时会解决这个问题,暂时请先按楼上的方法试试~

> 暴力注销掉。那个源已经关闭了。所以出错。

**Comment by myramses** [comment]
我也遇到了这个问题,是系统默认编码出了问题.有类似解决方案,例如:
https://blog.csdn.net/lqzdreamer/article/details/76549256

**Comment by Weot** [comment]
dotpy.py 第19行改成这样试试, 编码encoding='utf-8'  
with open(sourcePath, 'r', encoding='utf-8') as f:
