### ISSUE TITLE
超时错误

### ISSUE THREAD

**Issue by yyegithub** [EvilCult/iptv-m3u-maker#17]
tools.py，51行加了个timeout的捕获，避免了超时的时候导致无法运行，没怎么写过python，不知道加的对不对
        except socket.timeout as toe:
            header = toe.headers
            body = toe.read().decode('utf-8')
            code = toe.code

**Comment by EvilCult** [comment]
#21 
一堆琐事纠缠...一直也没机会更新...但是有勤快的好人帮我加上了......
