### ISSUE TITLE
抓取频道报错

### ISSUE THREAD

**Issue by pk49800** [EvilCult/iptv-m3u-maker#20]
[iptv-m3u-maker] python main.py                                                                                             master 
Checking[ 1 / 141 ]: CCTV-1综合
Checking[ 2 / 141 ]: CCTV-2财经
Checking[ 3 / 141 ]: CCTV-3综艺
Checking[ 4 / 141 ]: CCTV-4中文国际
Checking[ 5 / 141 ]: CCTV-5体育
Checking[ 6 / 141 ]: CCTV-5++体育赛事
Checking[ 7 / 141 ]: CCTV-6电影
Checking[ 8 / 141 ]: CCTV-7军事农业
Checking[ 9 / 141 ]: CCTV-8电视剧
Checking[ 10 / 141 ]: CCTV-9记录
Checking[ 11 / 141 ]: CCTV-10科教
Checking[ 12 / 141 ]: CCTV-11戏曲
Checking[ 13 / 141 ]: CCTV-12社会与法
Checking[ 14 / 141 ]: CCTV-13新闻
Checking[ 15 / 141 ]: CCTV-14少儿
Checking[ 16 / 141 ]: CCTV-15音乐
Checking[ 17 / 141 ]: 湖南卫视高清
Checking[ 18 / 141 ]: 江苏卫视高清
Checking[ 19 / 141 ]: 浙江卫视高清
Checking[ 20 / 141 ]: 东方卫视高清
Checking[ 21 / 141 ]: 北京卫视高清
Checking[ 22 / 141 ]: 广东卫视高清
Checking[ 23 / 141 ]: 深圳卫视高清
Checking[ 24 / 141 ]: 天津卫视高清
Checking[ 25 / 141 ]: 安徽卫视高清
Checking[ 26 / 141 ]: 山东卫视高清
Checking[ 27 / 141 ]: 湖北卫视高清
Checking[ 28 / 141 ]: 辽宁卫视高清
Checking[ 29 / 141 ]: 重庆卫视高清
Checking[ 30 / 141 ]: 江西卫视高清
Checking[ 31 / 141 ]: 河北卫视高清
Checking[ 32 / 141 ]: 黑龙江卫视高清
Checking[ 33 / 141 ]: 四川卫视
Checking[ 34 / 141 ]: 广西卫视
Checking[ 35 / 141 ]: 河南卫视
Checking[ 36 / 141 ]: 山西卫视
Checking[ 37 / 141 ]: 东南卫视
Checking[ 38 / 141 ]: 厦门卫视
Checking[ 39 / 141 ]: 云南卫视
Checking[ 40 / 141 ]: 宁夏卫视
Checking[ 41 / 141 ]: 新疆卫视
Checking[ 42 / 141 ]: 旅游卫视
Checking[ 43 / 141 ]: 内蒙古卫视
Checking[ 44 / 141 ]: 凤凰中文台超清
Checking[ 45 / 141 ]: 凤凰资讯台超清
Checking[ 46 / 141 ]: 凤凰香港台超清
Checking[ 47 / 141 ]: Newtv动作电影
Checking[ 48 / 141 ]: Newtv惊悚悬疑
Checking[ 49 / 141 ]: Newtv精品电影
Checking[ 50 / 141 ]: Newtv明星大片
Checking[ 51 / 141 ]: Newtv家庭剧场
Checking[ 52 / 141 ]: Newtv精品大剧
Checking[ 53 / 141 ]: Newtv金牌综艺
Checking[ 54 / 141 ]: Newtv精品记录
Checking[ 55 / 141 ]: Newtv精品体育
Checking[ 56 / 141 ]: Newtv北京纪实
Checking[ 57 / 141 ]: Newtv上海纪实
Checking[ 58 / 141 ]: Newtv纪实天下(电)
Checking[ 59 / 141 ]: Newtv全纪实
Checking[ 60 / 141 ]: Newtv欢笑剧场
Checking[ 61 / 141 ]: Newtv都市剧场
Checking[ 62 / 141 ]: 科幻电影
Checking[ 63 / 141 ]: 速度与激情
Checking[ 64 / 141 ]: 赌博电影
Checking[ 65 / 141 ]: 赌神全集新木乃伊
Checking[ 66 / 141 ]: 王晶导演
Checking[ 67 / 141 ]: 徐克导演
Checking[ 68 / 141 ]: 黄渤
Checking[ 69 / 141 ]: 徐峥
Checking[ 70 / 141 ]: 斯坦森
Checking[ 71 / 141 ]: 黄百鸣
Checking[ 72 / 141 ]: 陈小春
Checking[ 73 / 141 ]: 黄日华
Checking[ 74 / 141 ]: 甄子丹
Checking[ 75 / 141 ]: 李连杰
Checking[ 76 / 141 ]: 刘德华
Checking[ 77 / 141 ]: 成龙
Checking[ 78 / 141 ]: 周星驰
Checking[ 79 / 141 ]: 林正英
Checking[ 80 / 141 ]: 徐老师LOL故事
Checking[ 81 / 141 ]: CCTV-1综合
Checking[ 82 / 141 ]: CCTV-2财经
Checking[ 83 / 141 ]: CCTV-3综艺
Checking[ 84 / 141 ]: CCTV-4中文国际
Checking[ 85 / 141 ]: CCTV-5体育
Checking[ 86 / 141 ]: CCTV-5++体育赛事
Checking[ 87 / 141 ]: CCTV-6电影
Checking[ 88 / 141 ]: CCTV-7军事农业
Checking[ 89 / 141 ]: CCTV-8电视剧
Checking[ 90 / 141 ]: CCTV-9记录
Checking[ 91 / 141 ]: CCTV-10科教
Checking[ 92 / 141 ]: CCTV-11戏曲
Checking[ 93 / 141 ]: CCTV-12社会与法
Checking[ 94 / 141 ]: CCTV-13新闻
Checking[ 95 / 141 ]: CCTV-14少儿
Checking[ 96 / 141 ]: CCTV-15音乐
Checking[ 97 / 141 ]: 湖南卫视高清
Checking[ 98 / 141 ]: 江苏卫视高清
Checking[ 99 / 141 ]: 浙江卫视高清
Checking[ 100 / 141 ]: 东方卫视高清
Checking[ 101 / 141 ]: 北京卫视高清
Checking[ 102 / 141 ]: 广东卫视高清
Checking[ 103 / 141 ]: 深圳卫视高清
Checking[ 104 / 141 ]: 天津卫视高清
Checking[ 105 / 141 ]: 安徽卫视高清
Checking[ 106 / 141 ]: 山东卫视高清
Checking[ 107 / 141 ]: 湖北卫视高清
Checking[ 108 / 141 ]: 辽宁卫视高清
Checking[ 109 / 141 ]: 重庆卫视高清
Checking[ 110 / 141 ]: 江西卫视高清
Checking[ 111 / 141 ]: 河北卫视高清
Checking[ 112 / 141 ]: 黑龙江卫视高清
Checking[ 113 / 141 ]: 四川卫视
Checking[ 114 / 141 ]: 广西卫视
Checking[ 115 / 141 ]: 河南卫视
Checking[ 116 / 141 ]: 山西卫视
Checking[ 117 / 141 ]: 东南卫视
Checking[ 118 / 141 ]: 厦门卫视
Checking[ 119 / 141 ]: 云南卫视
Checking[ 120 / 141 ]: 宁夏卫视
Checking[ 121 / 141 ]: 新疆卫视
Checking[ 122 / 141 ]: 旅游卫视
Checking[ 123 / 141 ]: 内蒙古卫视
Checking[ 124 / 141 ]: 凤凰中文台超清
Checking[ 125 / 141 ]: 凤凰资讯台超清
Checking[ 126 / 141 ]: 凤凰香港台超清
Checking[ 127 / 141 ]: Newtv动作电影
Checking[ 128 / 141 ]: Newtv惊悚悬疑
Checking[ 129 / 141 ]: Newtv精品电影
Checking[ 130 / 141 ]: Newtv明星大片
Checking[ 131 / 141 ]: Newtv家庭剧场
Checking[ 132 / 141 ]: Newtv精品大剧
Checking[ 133 / 141 ]: Newtv金牌综艺
Checking[ 134 / 141 ]: Newtv精品记录
Checking[ 135 / 141 ]: Newtv精品体育
Checking[ 136 / 141 ]: Newtv北京纪实
Checking[ 137 / 141 ]: Newtv上海纪实
Checking[ 138 / 141 ]: Newtv纪实天下(电)
Checking[ 139 / 141 ]: Newtv全纪实
Checking[ 140 / 141 ]: Newtv欢笑剧场
Checking[ 141 / 141 ]: Newtv都市剧场
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 123, in <module>
    obj.run()
  File "main.py", line 32, in run
    urlList = listB.getSource()
  File "/home/acer/iptv-m3u-maker/plugins/listb.py", line 21, in getSource
    res = self.T.getPage(url, req)
  File "/home/acer/iptv-m3u-maker/tools.py", line 43, in getPage
    response = urllib.request.urlopen(request, context = ctx)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by CodeIntegrity** [comment]
作者是不是不维护了。。

**Comment by casojie** [comment]
好像是有些地址失效了，python不是很懂，有大佬跟进维护吗

**Comment by raycheng0** [comment]
因為這兩個網址已失效

https://github.com/billy21/Tvlist-awesome-m3u-m3u8/blob/master/list.md
https://www.sheng521.top/zyfx/zbfx

在 main.py 註釋以下這幾行就可以

       listA = lista.Source()
        urlList = listA.getSource()
        for item in urlList :
           self.addData(item)

        listB = listb.Source()
        urlList = listB.getSource()
        for item in urlList :
            self.addData(item)

**Comment by EvilCult** [comment]
#22  这此更新应该可以了
