### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't...

### ISSUE THREAD

**Issue by yyy123zc** [EvilCult/iptv-m3u-maker#28]
我不懂编程，下载的是Python 3.7.4 x64，系统是Windows10 x64 1909版本。
在运行到python main.py命令时，出现 “UnicodeDecodeError: 'gbk' codec can't” 错误，百度后都是Windows下东编码错误，试着修改，修改后能运行了。
就是在文件中搜索到with open，在其后括号内添加“, encoding='UTF-8'”。

非常感谢作者。
运行成功后tv.m3u8文件内中央台只有1和9，卫视也不全，希望能多加几个播放源。

第一个错误：
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    obj.run()
  File "main.py", line 25, in run
    Dotpy.getSource()
  File "G:\iptv-m3u\iptv-m3u-maker\plugins\dotpy.py", line 19, in getSource
    lines = f.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 8: illegal multibyte sequence
修改方法：
打开文件 路径\iptv-m3u-maker\plugins\dotpy.py，
定位到第18行，将
with open(sourcePath, 'r') as f:
改为
with open(sourcePath, 'r', encoding='UTF-8') as f:

第二个错误：
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    obj.run()
  File "main.py", line 35, in run
    self.outPut()
  File "main.py", line 64, in outPut
    f.write("#EXTINF:-1, group-title=\"%s\", %s\n" % (className, item[1]))
UnicodeEncodeError: 'gbk' codec can't encode character '\ufeff' in position 32: illegal multibyte sequence
修改方法：
打开文件 路径\iptv-m3u-maker\main.py，
搜索with open，有两处：
第49行，将
with open('tv.m3u8', 'w') as f:
改为
with open('tv.m3u8', 'w', encoding='UTF-8') as f:
第101行，将
with open('tv.json', 'w) as f:
改为
with open('tv.json', 'w', encoding='UTF-8') as f:

**Comment by yyy123zc** [comment]
已解决。根据 File "G:\iptv-m3u\iptv-m3u-maker\plugins\dotpy.py", line 19, in getSource 的提示，百度后找到原因：读文件的时候出现编码错误。 打开文件dotpy.py，定位到第19行，将
with open(sourcePath, 'r') as f:
改为
with open(sourcePath, 'r', encoding='UTF-8') as f:
现运行正常。

**Comment by EvilCult** [comment]
👍👍👍
