### ISSUE TITLE
能否考虑增加数据源？

### ISSUE THREAD

**Issue by MasterOfStar** [EvilCult/iptv-m3u-maker#29]
例如这个http://iptv.pdsu.edu.cn/

**Comment by EvilCult** [comment]
你这个…………教育网专用？

**Comment by MasterOfStar** [comment]
貌似不是教育网专用，可以外网访问

**Comment by EvilCult** [comment]
奇怪，可是我就打不开啊？

**Comment by MasterOfStar** [comment]
不该啊 我在家访问（浙江移动）是能打开的
![image](https://user-images.githubusercontent.com/21274896/75085567-9cdcdf00-5565-11ea-9ed5-4a3022bc13b3.png)
会不会是ipv6访问的问题

**Comment by MasterOfStar** [comment]
破案了，我ipv4 only 访问打不开，应该是只能ipv6打开

**Comment by EvilCult** [comment]
哦,那这个恐怕不能加入了.
不过有新的数据源欢迎分享!

**Comment by MasterOfStar** [comment]
https://545c.com/dir/210769-36350063-78fccb
这里面全是源

**Comment by EvilCult** [comment]
不错不错,我先看看

**Comment by sghsd** [comment]
https://github.com/iptv-org/iptv
这里有1500个中文源，不知道能不能用
