### ISSUE TITLE
无法解析数据源

### ISSUE THREAD

**Issue by JoJoJoinme** [EvilCult/iptv-m3u-maker#30]
在Win10上用PotPlayer测试可播放后，
将其发送到刷了webpad的安卓固件斐讯N1上，用kodi播放，却无法解析。

**Comment by EvilCult** [comment]
这就神秘了。
不过，下个版本or下下个版本会整体改为docker部署。
可以避免些这种奇奇怪怪的问题。
再等等吧。

**Comment by EvilCult** [comment]
#32
