### ISSUE TITLE
请问可以在群晖docker部署出个教程嘛

### ISSUE THREAD

**Issue by aliporcins** [EvilCult/iptv-m3u-maker#42]
您好，我想在群晖docker里部署您的项目，但是在注册表搜不到您的项目，请问您方便出个教程发布到docker上好拉取下载嘛？

**Comment by CodeIntegrity** [comment]
作者有说明手动部署方法，我试了下不是很难，几条命令的事，就是群晖部署的时候需要在套件中心安装git server，然后照着作者的方法在命令行输入命令就行了
